### PR TITLE
Enhance WithArgs variadic function support

### LINKED ISSUE #17: When using `WithArgs` should missing return values be treated as anything matchers?
This would allow the caller to only specify the return values they need and ignore the rest. I see potential "bugs" being reported here due to not being specific enough when specifying return values.

### LINKED ISSUE #18: Support for Optional Arguments
I took this example below from your readme, with small tweaks to use require/assert.  The first one is for illustration, the second test fails.

I don't see anything in the README that optional arguments are explicitly not supported. The generated gRPC service client always has an `opts ...grpc.CallOption` as the last argument, so the use case is typical to mock out the call to the service method.

The test below gives me this output:
```
test.run "^Test_AsShownInReadme|Test_WithOptional$" #gosetup
=== RUN   Test_AsShownInReadme
--- PASS: Test_AsShownInReadme (0.00s)
=== RUN   Test_WithOptional
    Test_WithOptional: mocka_optional_test.go:36: 
        	Error Trace:	mocka_optional_test.go:36
        	Error:      	Received unexpected error:
        	            	mocka: stub does not exist
        	Test:       	Test_WithOptional
--- FAIL: Test_WithOptional (0.00s)
FAIL

Process finished with exit code 1
```

```golang
package step_test

import (
	"testing"

	"github.com/MonsantoCo/mocka"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_AsShownInReadme(t *testing.T) {
	var fn = func(str string) int {
		return len(str)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123").Return(5))

	assert.Equal(t, 5, fn("123"))
}

func Test_WithOptional(t *testing.T) {
	var fn = func(str string, opts ...string) int {
		return len(str) + len(opts)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123").Return(5))

	assert.Equal(t, 5, fn("123"))
}
```

### PR DESCRIPTION
**Pull request by cmarfia**
# Changes

## Added
- New `SliceOf()`matcher that allows matchers for specific slice elements
- Examples for variadic functions
- Documentation to the README.md for variadic functions

## Changed
- `WithArgs()` has been updated to take in variadic arguments the same as how functions take them 
- `argumentValidaitonError` messages now show variadic arguments as `...type` instead of `[]type`

### CODE REVIEW

File: customArguments.go [hunk 1]
```diff
@@ -36,47 +36,87 @@ func newCustomArguments(stub *mockFunction, arguments []interface{}) *customArgu
 	}
 }
 
+// isArgumentLengthValid - returns whether or not the length of the provided arguments
```
Comment (cmarfia) [inline customArguments.go]: remove `-` before returns.

File: call.go [hunk 2]
```diff
@@ -13,6 +13,9 @@ type call struct {
 
 // Arguments returns the arguments that stub was called with.
 func (c call) Arguments() []interface{} {
+	// TODO - callout if a function is variadic should the
```
Comment (cmarfia) [inline call.go]: This will be covered by the TODO in `argumentValidationError.go`

File: customArguments.go [hunk 3]
```diff
@@ -36,47 +36,87 @@ func newCustomArguments(stub *mockFunction, arguments []interface{}) *customArgu
...
 
-		switch arg.(type) {
-		case match.SupportedKindsMatcher:
-			matcher := arg.(match.SupportedKindsMatcher)
-			if _, ok := matcher.SupportedKinds()[aType.Kind()]; !ok {
-				return nil, &argumentValidationError{
-					fnType:   functionType,
-					provided: arguments,
-				}
+		if isVariadicArgument(i, functionType) {
```
Comment (cmarfia) [inline customArguments.go]: I think I should swap the argument order here to keep the `functionType` as the first argument.

File: match/sliceOf.go [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+	return map[reflect.Kind]struct{}{
+		reflect.Slice: {},
+		reflect.Array: {},
+	}
+}
+
+// Match returns true when all value elements match their respective matchers
+func (m *sliceOf) Match(value interface{}) bool {
+	slice := reflect.ValueOf(value)
+	if _, exists := m.SupportedKinds()[slice.Kind()]; !exists {
```
Comment (cmarfia) [inline match/sliceOf.go]: This check can be remove since it is being handled by the caller.

File: match/sliceOf.go [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+		return false
+	}
+
+	if len(m.matchers) != slice.Len() {
+		return false
+	}
+
+	for i, matcher := range m.matchers {
+		indexValue := slice.Index(i)
+		if _, exists := matcher.SupportedKinds()[indexValue.Kind()]; !exists {
```
Comment (cmarfia) [inline match/sliceOf.go]: This check can be removed since it is being handled by the caller.

**Comment by cmarfia** [comment]
I Approve.

**Comment by cmarfia** [comment]
Missing test to see if `stub.implementation` put the current arguments on the call meta data.

File: CHANGELOG.md [hunk 6]
```diff
@@ -5,6 +5,14 @@ The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
...
 
 ## [Unreleased]
+## Added
+- New `SliceOf()` matcher that allows matchers for specific slice elements
+- Examples for variadic functions
+- Documentation to the README.md for variadic functions
+
+## Changed
+- `WithArgs()` has been updated to take in variadic arguments the same as how functions take them 
+- `argumentValidaitonError` messages now show variadic arguments as `...type` instead of `[]type`
```
Comment (poost-frey) [inline CHANGELOG.md]:
```suggestion
- `argumentValidationError` messages now show variadic arguments as `...type` instead of `[]type`
```

File: README.md [hunk 7]
```diff
@@ -297,6 +298,44 @@ fmt.Println(fn("123"))
...
+	log.Panic(err)
+}
+
+// omitting the variadic arguments will match if function was called without them supplied
+err = stub.WithArgs("B").Return(10)
+if err != nil {
+	log.Panic(err)
+}
+
+// providing the variadic argumnets will match exactly what was provided
```
Comment (poost-frey) [inline README.md]:
```suggestion
// providing the variadic arguments will match exactly what was provided
```

**Review by poost-frey — APPROVED** [review]
